/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xhs_ndkdemo_Hello */

#ifndef _Included_com_xhs_ndkdemo_Hello
#define _Included_com_xhs_ndkdemo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xhs_ndkdemo_Hello
 * Method:    callFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xhs_ndkdemo_Hello_callFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
